services:    
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=desiroo
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "9080:5432"

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BROWSER: on
    command: server /data --console-address ":9090"
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9090:9090"
    
volumes:
  minio-data:
    driver: local
